#!/bin/sh

while read file
do
fullpath="$(pwd)/$file"
 case "$1" in
 "s") feh --bg-scale "$file" 
	notify-send "Wallpaper changed." ;;
 "y") xclip -selection clipboard "$file" 
	notify-send "copied to clipboard"  ;;
 "d") [ "$(printf 'No\nYes' |  dmenu -p 'Delete all of the selected file(s)?')" = "Yes" ] && rm "$file" && 
	notify-send "File(s) Deleted" ;;
 "f") convert -flop "$file" "$file" ;;
 "r") convert -rotate 90 "$file" "$file" ;;
 "R") convert -rotate -90 "$file" "$file" ;;
 "G") gimp "$file" & ;;
 esac
done
